# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-27 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MicroCourse', '0002_auto_20180827_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
