# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-28 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MicroCourse', '0003_usertype_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='teacher',
            field=models.IntegerField(default=0),
        ),
    ]
