# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-27 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MicroCourse', '0005_gradeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MicroCourse.GradeInfo')),
            ],
        ),
    ]
