# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-29 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MicroCourse', '0007_courseinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='volume',
            field=models.CharField(default='上册', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='class1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='MicroCourse.UserType'),
        ),
    ]
