# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-22 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MicroCourse', '0009_auto_20181016_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskinfo',
            name='type',
        ),
        migrations.DeleteModel(
            name='TaskType',
        ),
    ]
