# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-22 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MicroCourse', '0010_auto_20181023_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
