# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-22 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MicroCourse', '0011_taskinfo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
