# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-29 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MicroCourse', '0014_testpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='name',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
