# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-31 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MicroCourse', '0017_auto_20181101_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='takeExamUserCount',
            field=models.IntegerField(default=0),
        ),
    ]
