# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-11 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MicroCourse', '0019_auto_20181111_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
