# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-11 13:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MicroCourse', '0021_auto_20181111_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 11, 21, 56, 25, 436425)),
        ),
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 11, 21, 56, 25, 435573)),
        ),
    ]
